#ifndef LIBRARIES_MOSFET_MOSFET_H_
#define LIBRARIES_MOSFET_MOSFET_H_


#define MOSFET_INIT DDRB |=(1<<PB3)

#define TIMER1PRESCALERMASK TCCR1B &= ~((1<<CS10) | (1<<CS10) | (1<<CS10));
#define TIMER1_PESCALER_64  TIMER1PRESCALERMASK; TCCR1B |= (1<<CS10)|(1<<CS12)
#define TIMER1_PESCALER_OFF TIMER1PRESCALERMASK; TCCR1B &= ~( (1<<CS10)|(1<<CS12) )



#endif /* LIBRARIES_MOSFET_MOSFET_H_ */
